sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product testn-082
env:
  global:
    -
      # LTD_AWS_ID
      secure: pTKkpltsZMYdDe4e6lVhTDFm9mQeq8hsWdEQ3T1XhucenhRThNmioORluuMKoQy0ma+wljzWLOyIS/vzPph8gOMbGylANwfdy3M+/Iu6GPmHHrlb/6PZ1C1x2ygTG+bqfJLFcOXn5DDMs1Niw7+PCjdYg9NSqYJh1NSGHWeKDFHRT3gPGqMxTtb44QnwUlzsqWPJ5d10FGlahQaPZoIHmgikWEETLFa9N+Ht/egiXTvNXlipNrwxnCaHKdNmXTPhjiO+/f/OP55In77GxQo6C7j81J8PIrvoPbC0IiBAjSuJDSpxTwJImLBp33H/Lof/ci2P84yd7treJZCZ82cbGWCzke4JA2vfGywmviTny6cXzgEfWFoSiebg3SHrubM5pbXmND8LbNx1lnSmlK+qL4pRaompZpYS7gsUPUpPpjSkkut7V54YhK1+3pCGYmzWDqYlHJPpfYF2YHEWQM4xlAEg2G0NZJQr5sWDThcWcDLbapM29HR6D9dhZyFt+9TUVtKsVm62gHyppEIWtYoEvUfrvEbsT8lyCDlq62diphcO8jzF9tSvRxHpBnDwsIMbPwTCRQleBj/HCh3yhTyt2CsJ+UWMc+fPcMkZ2TiiqbKafU93+RLr2evIRfan5SBV66ZWh7TJV5UhfAgBGzngyr10HK3m8Wu6mkD0HhjLKZI=
    -
      # LTD_AWS_SECRET
      secure: gDEX12jLJVSP0xNiOpmIESnZFRpj1W7JCOrOHd38RrcGBd6yiQt+SSkvgFNCZzEiKiNyuPNwe9uaQJFVXBNyemah1redjqcJ7XCpgj8dNBlpHyXO3NemIi0SinAGLtmIV1sD8QBPAfYLuFzO2d3+eMD7fOU+gCNoj9O8WHhGGGUImPUk1mWmOOY8xzb6VGcWynB+pDhPrmhaEDUI5dPPGOIcoRiF1irPem3Emke9wR0XSyicXokeB98+NzhV22Yyrvc1hsTqdCGc4fxZAggCbcKpdGtBlOdj+nbklbnOLvpcOTPaDEGI1EUGt8OPs7SI1WpsDqDrGqmE42HO279u5UneX6fHvrP7EnM2KPYPxfrcgpV4Ma+bEKX0dHZ90eZ0doBrLlKQZYkxGg35LDIevzF5zEMFzd1MuiGot7hBdLbuQNsr/rihRoOCF4p0LWK4m6MHT7zwRlRPclXaZ+5Z8OECu+4hhdwnBqX5aqFFWHpiBa7QgzNt2jrERPMTEsD8RHaP/UpscUwNHhVMAPqLUUlqOMsEYevvJpTO/imivukfBloXO1mYBt4W4gWU17a+uuNQEuAm/hMb3XkfItW9lJXifgA8b2TDgYHj5yBLYpuYMhufs6OwRSP9bwvMqyfz8ijO6l2E7FWOMjuR2Nq/MUaidw6tCzS1PDb/ruJgztw=
    -
      # LTD_USERNAME
      secure: UJze1PVm35S4xLlNwJfcVngdo5OylNZOw6NMR55zpMMmttCemRqsIQluQgcoTufC4Ysl8G4i3VBizoDIgKinAxS8MHppPYXV8Q8U9iY7ni/dZj6RSCTzDOF5IUdKqhQ2cnzrBUqkwbjqtmAj7ZYw0RkZvYEvNhRNT8osbhi2xuNX/QpGmjon/sjfIryNjX/BQbcOG5S0lUFwn+fUHG7Bv+7YkrJmleHoWzIW9nYvn9h2k+0dGNOWw2PSAzjkE+mi7iVtZz+zP5HTHQ2UAEgrGd7o1v4bpHztsq+13JU4ZbzW/Y1N2e6iSB0Z8RAiSsMVhfLdQhMW3tMJwUhKnoEUptKDTa8WQKgaGCb5x3KbITzafQl+Nkt16Tr1/4uqGz4895IBW5yyvtZ+TOm9ynqQBwO+F5FBToJTWCb29J0Ch+BHTdEHnDscuRlw1eupP6yc8Mmy7SFjBeb0s63mvQCu3iW/GdEQa/ej8R/21oyBt/pYzCnXW87ykS5WWyLcxdy68W4yKuP50dlnT9i0oNF72zR3bfeOc/N1K8hyUD5D8pGvskmumjXgx6MxB1UqGCRr/0gASbaR8SArXkMJKTStK3zxa4+rHi1Aad/kkKvrz/jj6lxByrH+pUOY10AtPP+FD5r4yxUL4OsiuNZdLOSdStIHVbL4ifA/M/PSQYJj/NQ=
    -
      # LTD_PASSWORD
      secure: aMoOTjhKSmDlFF2OoqwRRPL/LkI0//OznaOBW6aZUPy3GN40CJrRfHgGkP9J4BpTrrCYpwRMPmT+4+qBSOOy14wAXEpQYaxhUX5DDMl/NzhwQrCKghl3kk+mMOc1cEXExuugPKoKhvEcluXuxLUXutQAh4Cx0D3VKCRZmnSPsLLbZ9FQwmRFylvJnMNf/q5VPDoKxzmOsnY95ri7d9QfJmIN3LTEeHm68GTSLbRxTLgOT4gvLKI2qJdCtoQvRtte/xWX8ghmE0WCDScXgbsAmsfWtwKvf/iJC8uNCEHqi6ClaKMvnIViNaRfS/XdMOW3xTyiznI6r/wzNd1BqV1Z0VsaJNFqt4JNeVLqq6XK4SA02za8GZNlr4gF4w1Zq0lgk1QDULodpfl7Si8cQ6P3i/xhFRDW6DvWlK7t6QuGBDn3YpDicbT88lH0eJSCx4TN0Cc3hknfOsfRIhMsQpkpweHa93TBNnUF9PRgBMofftOi/VIDNlRC61tFnnjwc9fXmj+8wzlWe58iR3dX4lhDJubJqwyF8Btgo/lVeOpOxp+Wznosq43TLjMuNr9i6YqKcz8yXQCAXTYH9xfTjuEixY4/jP/Mge97wFJcQbEEYxHTz+istESYZpaaM6BKnIw/KWt5+m7i1WhFzmYOKtwGC5K5D/iV271jPXMqvhC9Ybk=
